[Interface]
PrivateKey = "KJ/seoQUETgXoUlKwhe48Vq/DThFx0ylklcLY5biBGo="
Address = "10.0.0.3/32"

[[Peer]]
PublicKey = "S7gePhdPibDJLgDWbRq65wwudzMgpR3vy/RsERaVtys="
AllowedIPs = "10.0.0.1/24"
# Endpoint = "127.0.0.1:47789"
# Endpoint = "172.29.70.44:47789"
# Endpoint = "69.164.244.81:47789"
Endpoint = "170.106.143.75:47789"

