[Interface]
PrivateKey = "oPyKessWgQy8EzK1gee54XcyBwmm5KfN8AnAPX9Gx3Q="
ListenPort = 47789
Address = "10.0.0.1/24"
TransportID = "trojanServerID"

[[Peer]]
PublicKey = "14nWLDf+tZ6CXwC6WNEq/VWsbOoSr/yggbyRX17goEM="
AllowedIPs = "10.0.0.2/32"
TransportID = "trojanClientID"

[[Transport]]
ID = "tlsServerID"
Type = "tls"
Cfg.ServerName = "localhost"
Cfg.CertFile = "./samples/cert.pem"
Cfg.KeyFile = "./samples/key.pem"

[[Transport]]
ID = "trojanServerID"
Type = "trojan"
Underlying = "tlsServerID"
Main = true
Cfg.RedirectHost = "127.0.0.1"
Cfg.RedirectPort = 8080
Cfg.Passwords = ["password"]

[[Transport]]
ID = "tlsClientID"
Type = "tls"
Cfg.ServerName = "localhost"
Cfg.SNI = true
Cfg.InsecureSkipVerify = true

[[Transport]]
ID = "trojanClientID"
Type = "trojan"
Underlying = "tlsClientID"
Cfg.Password = "password"
